examples/run_vasp.py

use repr(Exception) instead Exception.msg

---

examples/run_vasp.py

add simple SI example

---

.pre-commit-config.yaml
MANIFEST.in
aiida_vasp/__init__.py
ops/update_version.py
setup.json
setup.py

The pre-commit hook 'version' enforces consistency between
* git tags
* setup.json
* top-level __init__.py.__version__
fix #26

Reset version and add pre-commit hook to ensure consistency

---

aiida_vasp/calcs/tests/test_vasp.py
aiida_vasp/parsers/tests/test_base_parser.py
aiida_vasp/utils/fixtures/__init__.py
aiida_vasp/utils/fixtures/calcs.py
setup.json
tox.ini

Add unit tests for BaseParser so the new pymatgen parser can be based on it.
fix #44

Test base parser

---

aiida_vasp/data/pymatgen/vasprun.py
aiida_vasp/parsers/pymatgen_vasp.py
aiida_vasp/parsers/tests/test_pymatgen_parser.py

Fix #50 (complete with unit test)

pmg-vasprun-parser: Add forces output node

---

aiida_vasp/data/pymatgen/vasprun.py
aiida_vasp/parsers/pymatgen_vasp.py
aiida_vasp/parsers/tests/test_pymatgen_parser.py

Fix #52 (complete with unit test)

pmg-vasprun-parser: add energy and other outputs

---

.travis.yml
aiida_vasp/data/pymatgen/vasprun.py
aiida_vasp/parsers/pymatgen_vasp.py
aiida_vasp/parsers/tests/test_pymatgen_parser.py
tox.ini

pmg-vasprun-parser: Add bandstructure parsing

---

aiida_vasp/data/pymatgen/vasprun.py
aiida_vasp/parsers/pymatgen_vasp.py
aiida_vasp/parsers/tests/test_pymatgen_parser.py

pmg-vasprun-parser: add dos

---

aiida_vasp/parsers/pymatgen_vasp.py
aiida_vasp/parsers/tests/test_pymatgen_parser.py

pmg-parser: add suppress options for DOS and bandstructure output nodes

---

aiida_vasp/calcs/tests/test_vasp.py
aiida_vasp/calcs/vasp.py
aiida_vasp/utils/fixtures/__init__.py
aiida_vasp/utils/fixtures/calcs.py
aiida_vasp/utils/fixtures/data.py

fix writing of unordered poscar files (+test).

---

aiida_vasp/io/pymatgen_aiida/vasprun.py
aiida_vasp/parsers/pymatgen_vasp.py
aiida_vasp/parsers/tests/test_pymatgen_parser.py

adapt ouput nodes to be closer to qe & update tests

---

setup.json

add an entry point for pymatgen parser.

---

.travis.yml
examples/run_vasp.py

fix #78 (reinstate pre-commit tests)

---

aiida_vasp/backendtests/common.py
aiida_vasp/backendtests/vasp.py
aiida_vasp/calcs/base.py
aiida_vasp/calcs/maker.py
aiida_vasp/calcs/tests/test_vasp.py
aiida_vasp/calcs/vasp.py
aiida_vasp/calcs/w90win.py
aiida_vasp/data/archive.py
aiida_vasp/io/cif.py
aiida_vasp/io/incar.py
aiida_vasp/io/parser.py
aiida_vasp/io/potcar.py
aiida_vasp/io/tests/test_incar.py
aiida_vasp/io/vasprun.py
aiida_vasp/parsers/tests/test_base_parser.py
aiida_vasp/parsers/vasp.py
ops/update_version.py

See Issue https://github.com/DropD/aiida-vasp/issues/89 
- Updated logic for is_md, is_relaxation and is_static in io/vasprun.py
- Fixed read_cont in parsers/vasp.py
- Added 'CONTCAR' to always retrieve list in calcs/vasp.py
- Fixed minor typo in Docstring of _prepare_for_submission in calcs/base.py

Issue #89: Revised logic in vasprun parser + fixed the read_cont

---

CHANGELOG.md
README.rst
doc/source/index.rst
setup.json

Add changelog

---

CHANGELOG.md
aiida_vasp/__init__.py
ops/update_version.py
setup.json
setup.py

update requirements, PyPi description and keywords

---

aiida_vasp/io/chgcar.py
aiida_vasp/io/doscar.py
aiida_vasp/io/eigenval.py
aiida_vasp/io/incar.py
aiida_vasp/io/kpoints.py
aiida_vasp/io/outcar.py
aiida_vasp/io/parser.py
aiida_vasp/io/poscar.py
aiida_vasp/io/potcar.py
aiida_vasp/io/tests/test_chgcar_io.py
aiida_vasp/io/tests/test_doscar_io.py
aiida_vasp/io/tests/test_eigenval_io.py
aiida_vasp/io/tests/test_kpoints_io.py
aiida_vasp/io/tests/test_outcar_io.py
aiida_vasp/io/tests/test_poscar_io.py
aiida_vasp/io/tests/test_vasprun_io.py
aiida_vasp/io/tests/test_wavecar_io.py
aiida_vasp/io/vasprun.py
aiida_vasp/io/wavecar.py
aiida_vasp/io/win.py
aiida_vasp/parsers/vasp.py
aiida_vasp/utils/fixtures/data.py

This also makes the file parser constructor signatures backwards compatible.

simplify file parser interfaces

---

.coveragerc
.pre-commit-config.yaml
.travis.yml
aiida_vasp/data/paw.py
aiida_vasp/data/potcar.py
aiida_vasp/utils/aiida_utils.py
run_ci_tests.sh
tox.ini

fix #138 
Also, test against both the stable and devleop version of `aiida-core` on travis.

Update aiida-core usage to post workflows merge 

---

aiida_vasp/commands/potcar.py

import the verdi data cmd group correctly in aiida-dev

---

examples/run_vasp.py

The original version was giving a cross-product complaint in VASP, the following modified version works

Fixed bug in Si test example

---

aiida_vasp/parsers/parser_settings.py

Fixed an issue with iterable over None when no parser_settings

---

setup.json

fixes: #198 
blocks:
is blocked by:
Updated parsevasp dependency to fix #198 and other non-reported bugs

Updated parsevasp dependency

---

AUTHORS.md
CHANGELOG.md
README.rst
aiida_vasp/__init__.py
setup.json

Prepare release

---

README.rst
doc/source/index.rst
doc/source/index_old.rst
setup.json

Update links after moving to aiida-vasp organization

change all the links to point to the new repo url

---

aiida_vasp/io/tests/test_vasprun_io.py
aiida_vasp/io/vasprun.py

Added `total_energies`, `maximum_force` and `maximum_stress` to the vasprun parser. Those are rather frequently used.

Added parser quantities to output_parameters

---

.travis.yml
aiida_vasp/workchains/converge.py
aiida_vasp/workchains/relax.py
aiida_vasp/workchains/verify.py

fixes:
#229 
blocks:
is blocked by:
Fixes the docstring errors mentioned in #229. Also cleaned up the methods that verify the next workchain.

Fix verifynextwc docstrings

---

doc/tutorial/kickstart.rst

fixes:
blocks:
is blocked by:
This is documentation to kick-start AiiDA-VASP calculation. One workable procedure of setting up AiiDA-VASP is very needed to feel AiiDA for VASP users. This document contains preparing conda environment, installing PostgreSQL, AiiDA-core, AiiDA-VASP, setting-up AiiDA, and running an example calculation.

Documentation to kick-start AiiDA-VASP calculation

---

examples/run_bare_calc.py

fixes:
blocks:
is blocked by:
A new example of submitting non-workflow calculation that works with aiida-core v1.0.0a4. This is made to be similar to the QE instruction written in the AiiDA tutorial (May–June 2018). This example may replace `run_legacy.py`. Older aiida-core is probably not supported.

Add an example of submitting non-workflow calculation

---

aiida_vasp/io/vasprun.py
aiida_vasp/test_data/disp_details/#vasprun.xml#
aiida_vasp/workchains/vasp.py

fixes:
blocks:
is blocked by:
Removed alternative quantities for the energies and added the relay of forces and stress to the VASP workchain, which was missing

Fix parser inconsistencies

---

aiida_vasp/calcs/base.py
aiida_vasp/calcs/immigrant.py

This is a small fix for immigrant to pass potential_mapping and potential_family correctly.

Migration beta

---

CHANGELOG.rst
aiida_vasp/__init__.py
setup.json

Preparing for release 0.3.0

---

doc/requirements.txt
doc/source/getting_started/code.rst

* Added sphinx rtd in requirement.txt as it's used by default in the
docs Makefile
* Fixed misindentation in doc page on adding a code

Minor documentation fixes

---

aiida_vasp/commands/options.py
aiida_vasp/commands/potcar.py
aiida_vasp/commands/tests/test_potcar_cmd.py

fixes:
#173 
blocks:
is blocked by:

Updated help text for POTCAR handling

---

aiida_vasp/calcs/base.py

fixes:
#84 
blocks:
is blocked by:

Updated to account for all VASP output files

---

aiida_vasp/workchains/relax.py

fixes:
#289 
blocks:
is blocked by:

Fixed wrong call to nanmax

---

aiida_vasp/calcs/tests/test_vasp.py
aiida_vasp/calcs/vasp.py

fixes:
blocks:
is blocked by:
In this PR we enable the recent introduction of the `provenance_exclude_list` https://github.com/aiidateam/aiida-core/pull/3720. This enables us to exclude the `POTCAR` file from the repository and thus also make a proper release.

Excluded the POTCAR file from the storage in the repository

---

setup.json

fixes:
#317
Here we add a trove classifier for AiiDA.

Added AiiDA trove classifier

---

doc/source/getting_started/conda.rst
doc/source/getting_started/test_run.rst
doc/source/tutorials/band_structure_electrons.rst
doc/source/tutorials/bulk_modulus.rst
doc/source/tutorials/bulk_modulus_2.rst
doc/source/tutorials/fcc_si_step1.rst
doc/source/tutorials/run_vasp_builder.rst

fixes:
blocks:
is blocked by:
I have examined whether "Getting Started" and "Tutorials" sections in docs work with the latest aiida-core and aiida-vasp.
Environment:
- aiida-core: e8d1c90d8 Mon Apr 27 14:29:29 2020 +0200 Revise update-dependency flow to resolve issue #3930 (#3957)
- aiida-vasp: c0c9032 Mon Apr 27 15:28:34 2020 +0200 Fixed migration of the Wannier90 interface (#341)

Update tutorial documents

---

doc/requirements.txt

Fixes RTD compile failure due to missing `sphinxcontrib-details-directive`.

Added sphinxcontrib-details-directive to requirements

---

README.rst
codecov.yml

Here we replace the Coveralls badge with the one from Codecov due to recent change.

Added Codecov badge and removed Coveralls

---

.github/workflows/ci.yml
codecov.yml

Enabling the rest of the code for coverage analysis.

Enabled the remaining code for coverage analysis

---

setup.json

Cleaning the config with more accurate Trove classifiers.

Updated the setup json file

---

README.rst

Here, we add a few more badges that might be useful.

Updated the readme to include more badges

---

.github/workflows/ci.yml
README.rst

Adding badges to a table and increasing build timeout.

Added badges into a table and increase build timout

---

setup.json

Restructuring of the `setup.json` file.

Reshuffled content in setup

---

doc/source/concepts/immigrations.rst
doc/source/getting_started/profile.rst

Two minor updates of the documentation. In the develop branch, `git describe` gives
```
% git describe
v0.1.0-612-ga1f3339
```
Do we need rebase from master before merging this PR?

Minor updates of documentation

---

MANIFEST.in

fixes: #373
blocks:
is blocked by:
Include the tags.yml in the MANIFEST.in - then it will be included in the source distribution to be installed.

Updated MANIFEST.in to include tags.yml

---

doc/source/developments/developments.rst
doc/source/developments/general.rst
doc/source/index.rst

Here we update the documentation with motivation to contribute etc. We also add information that the development is a community effort etc.

Added notes about contribution

---

.pre-commit-config.yaml
aiida_vasp/workchains/bands.py
aiida_vasp/workchains/tests/test_bands_wc.py

Update for Issues #396. Special point symbols are obtained from seekpath in the BandWorkChain, but these symbols (labels) were not attached to resulting BandsData. This update attaches the symbols to the cloned BandsData.

BandWorkChain update

---

aiida_vasp/parsers/file_parsers/vasprun.py

A bugfix to the recently added status of the ionic and electronic convergence.

Fixed error in the check of the ionic and electronic convegence status

---

aiida_vasp/workchains/vasp.py

Here we make sure that the label set on the workchains is passed to the calculation.

Pass label set at WorkChain to CalcJob

---

aiida_vasp/data/potcar.py
aiida_vasp/data/tests/test_potcar.py

Previously, one has to manually migrate teh POTCAR groups using `verdi data vasp-potcar migratefamilies` command (#491).
With this PR, when `PotcarData` fails to match potcars but found eligible old groups, the migration will be performed and the  matching process retried. This makes the code fully backward compatible and no manual migration will be necessary.
fixes:
blocks:
is blocked by:

Enable automatic migration for the POTCAR groups

---

CHANGELOG.rst
aiida_vasp/__init__.py
setup.json

Merging release `v2.1.1` back into `develop`.

Merge v2.1.1 develop

---

aiida_vasp/assistant/parameters.py
aiida_vasp/workchains/converge.py

regarding the volume_change input.
Discussed in issue #519
fixes:
convergence workchain with compressed structure
blocks:
is blocked by:

small bugfix in aiida_vasp.workchains.converge

---

aiida_vasp/workchains/vasp.py

A small fix. This fixes `KeyError: 'ERROR_CALCUlATION_NOT_FINISHED'`.

Fix misspelling

---

doc/source/concepts/parameters.rst
doc/source/workchains/writing_workchains.rst

Closes #560. Update documents to reflect the discussion on precedence of parameters,
fixes:
blocks:
is blocked by:

Update docs for overriding policy on parameters

---

setup.json

It seems we need to update parsevasp dependency.

Update parsevasp version

---

setup.json

Need to follow parsevasp git commit hash.

Bump parsevasp git commit hash

---

aiida_vasp/calcs/vasp.py
aiida_vasp/parsers/content_parsers/outcar.py
aiida_vasp/parsers/content_parsers/vasprun.py
aiida_vasp/parsers/neb.py
aiida_vasp/parsers/tests/test_node_composer.py
aiida_vasp/parsers/vasp.py
aiida_vasp/workchains/vasp.py
examples/run_vasp_lean.py
setup.json

Adapting the handlers to do basic `ALGO` switching and increase of `NBANDS` when needed. As a result of work on the ACWF study.

Tailored handlers for ACWF study

---

aiida_vasp/calcs/neb.py
aiida_vasp/workchains/neb.py

fixes:
blocks:
is blocked by:
Fix a silly bug when writing inputs for a NEB calculation. It was probably introduced when trying to make it also work for CifData input - the initial structure is used as all intermediate images 😵.

fix a bug when generating inputs for NEB calculations

---

.github/workflows/ci.yml
CHANGELOG.rst
aiida_vasp/__init__.py
aiida_vasp/calcs/vasp.py
aiida_vasp/parsers/content_parsers/outcar.py
aiida_vasp/parsers/content_parsers/vasprun.py
aiida_vasp/parsers/neb.py
aiida_vasp/parsers/tests/test_node_composer.py
aiida_vasp/parsers/vasp.py
aiida_vasp/workchains/vasp.py
codecov.yml
examples/run_vasp_lean.py
setup.json

A commit that deviates from develop branch to offer support for core v1, in additions to extentions to the error handlers that was needed for the ACWF study. These are disabled by default, but can be enabled. Pylint etc. has also been disabled.

Deviating from develop to maintain a version that supports core v1

---

aiida_vasp/calcs/tests/test_neb.py
aiida_vasp/calcs/tests/test_vasp.py
aiida_vasp/utils/fixtures/data.py
aiida_vasp/utils/fixtures/environment.py
aiida_vasp/utils/tests/test_aiida_utils.py
pyproject.toml

Fixed the test profiles and pinned aiida core after necessary bugfix https://github.com/aiidateam/aiida-core/pull/5804.

Pinned to new release of aiida core and fixed profile tests

---

aiida_vasp/calcs/tests/test_vasp.py

fixes #479 
Here we introduce a test to check the exit code when some of the critical files are missing

Added test to check the exit code when critical files are missing

---

pyproject.toml

Updated contact information of project

---

README.rst
docs/source/getting_started/install.rst
docs/source/index.rst

Added link to discussion board. Also added support section in docs.

Added Matrix link and support section in docs

---

AUTHORS.rst
LICENSE.txt

Updates to the `LICENSE` to reflect work after the new development team took on over after Rico left from EPFL. Also updated the `AUTHORS` file accordingly.

Updated license and author file

---

docs/source/support/general.rst
docs/source/tutorials/bulk_modulus.rst

Added missing file to render the support part of the documentation.

Added support file

---

docs/source/support/general.rst

Fixed issue with README extraction for the support section in the docs.

Fix extraction from README in support doc

---

AUTHORS.rst
codecov.yml

Updated author list and prepped codecov for large PR with a likely drop in coverage.

Updated authors and prepped coverage to take large bulk of update

---

README.rst
docs/source/getting_started/install.rst
docs/source/support/general.rst

Here we fix the issue in `README` (duplicated references) that cause the upload of the release `v3.0.0` to fail due to the extraction of `long_description` from `README`.

Updated README and docs with references

---

aiida_vasp/data/potcar.py
aiida_vasp/data/tests/test_potcar.py
aiida_vasp/parsers/content_parsers/potcar.py
aiida_vasp/utils/fixtures/data.py

Here we remove the remaining dependencies on `pymatgen`.

Removed pymatgen calls from POTCAR parser

---

.readthedocs.yml

Updated config file to support new syntax. This also enables us to use a more recent Python version.

Updated RTD to use more recent Python version

---

CHANGELOG.rst
aiida_vasp/__init__.py

Preparing for the `v3.0.1` release.

Release v3.0.1

---

aiida_vasp/data/archive.py

Disable pylint warnings for `aiida-core>=2.5.0`

---

.coveragerc
.github/workflows/ci.yml
.github/workflows/nightly.yml

Small fixes to ensure that the needs for codecov v4 action are addressed.

Fixing issues with the coverage token resulting from the upgrade to action v4
