aiida-vasp/aiida-vasp

- aiida_vasp/calcs/maker.py
* paw_map is no longer guessed from the 'kind'
* User always needs to define which paw_map is used
* 'default' paw_maps can be defined
This is done because potentials (and which are recommended) changes between minor versions in VASP. As a result, it depends on which exact potentials the user imported what should be the default.
> Simplify behavior for getting paw_map

- aiida_vasp/data/pymatgen/vasprun.py
- aiida_vasp/parsers/pymatgen_vasp.py
- aiida_vasp/parsers/tests/test_pymatgen_parser.py
fix #35 
* Add a test for the case of a vasprun.xml that is truncated after first ionic step
* Add some documentation of limitation that a complete ionic step must be in the `vasprun.xml`
* Add `final_structure` property to `VasprunToAiida`
> Test pymatgen based parser with broken xml

- aiida_vasp/backendtests/data/INCAR
- aiida_vasp/io/incar.py
- aiida_vasp/io/tests/test_incar.py
- aiida_vasp/utils/fixtures/data.py
Fixes #70.
The repeated values are of the form ``int*int*..*value``, as described in http://cms.mpi.univie.ac.at/wiki/index.php/MAGMOM.
The multipliers are multiplied together when parsing, and the value is then given as ``{'repetitions': int, 'value': int / float}``.
> Add support for parsing 'repeated' values

- .gitignore
- .travis.yml
- CHANGELOG.md
- aiida_vasp/data/potcar.py
- aiida_vasp/data/tests/test_potcar.py
- aiida_vasp/io/outcar.py
- aiida_vasp/io/tests/test_outcar_io.py
- aiida_vasp/test_data/outcar/OUTCAR
- aiida_vasp/utils/fixtures/data.py
- ops/run_coveralls.py
- requirements-dev.txt
- setup.json
- tests_pytest/conftest.py
- tox.ini
fixes #125
`get_potcars_from_structure` was looping over `kind.symbol`s, now correctly loops over `kind.name`s. This was stopping it from working correctly for structures with kind names differing from the kind symbols.
> fix PotcarData.get_potcars_from_structure and #125

- .travis.yml
- aiida_vasp/commands/tests/test_potcar_cmd.py
- tox.ini
Add a test that calls `verdi data vasp-potcar` on the command line, to make sure it works.
Expand testing to cover aiida versions 0.11.4, current stable, `develop` branch. These tests are executed in parallel on travis
> Test cli access

- aiida_vasp/utils/aiida_utils.py
- aiida_vasp/utils/tests/test_aiida_compat.py
- examples/run_vasp.py
fix #142 
Updated the examples to use either the `inputs_template` or the `builder` interface, depending on the aiida version. This means, the examples are valid for aiida_core v0.10.0 + now.
> Update run_vasp.py examples

- aiida_vasp/io/parser.py
- aiida_vasp/parsers/file_parser_definitions.py
- aiida_vasp/parsers/tests/test_vasp_parser.py
- aiida_vasp/parsers/vasp.py
- aiida_vasp/utils/extended_dicts.py
Quantities can now have 'alternatives', which will be parsed, if the main quantity can not be parsed, due to missing files. The 'alternativees' can be set as an optional card in the dictionary defining the original quantity. This should take care of the issue of priority of files from which a quantity should be parsed in case, that it can be parsed from more than one. The general policy here should be that quantity names are unique.
For this reason the 'quantities' have been promoted to objects inside of the VaspParser, which can be initialised based on the dictionary provided in the FileParsers. This should keep adding new quantities to the FileParsers relatively simple.  
In addition this allowed for a bit of cleanup in the VaspParser, because I could now get rid of all of the …
> Added support for parsing 'alternatives' + clean up

- aiida_vasp/parsers/tests/test_vasp_parser.py
- aiida_vasp/parsers/vasp.py
- aiida_vasp/utils/extended_dicts.py
My previous update had at least two bugs in it. 
- The warning ensuring that quantity identifiers are unique was in the wrong place checking the wrong thing and therefore doing nothing.
- In case that an alternative quantity representing a node was parsed, it would not have gotten the correct link name.
Both issues did not have any effect currently, because there are no quantities with alternatives or non unique quantity identifiers.
> Bugfix: ensuring quantity name uniqueness + node link names for quantities with alternatives

- aiida_vasp/parsers/vasp.py
This bug fix will change the way `quantity.is_node` is set from `quantity.name == quantity.nodeName` to `quantity.nodeName in LINKNAME_DICT`. This allows to move setting `quantity.is_node` to the constructor of `ParsableQuantity`, which will make it independent of the loading order of quantities.
This is also the first step of separating 'output_nodes' from quantities, where in the long term `LINKNAME_DICT` will become `output_node_definitions`.
> Bugfix: Setting 'quantiy.is_node' depends on loading order of quantities

- aiida_vasp/parsers/vasp.py
- aiida_vasp/utils/aiida_utils.py
- aiida_vasp/utils/tests/test_aiida_compat.py
- aiida_vasp/workflows/base.py
- aiida_vasp/workflows/restart.py
In AiiDA-core some things have been moved / removed. Add compatibility layers to stay compatible with both the 1.0 and the 0.12 series:
* get `aiida.work.db_types` and `aiida.orm.data.base` members through `get_data_class` and `get_data_node` now
* `BaseRestartWorkchain`: replace `on_destroy` with `on_terminated` only in the newer version
> fix latest compatibility issues for aiida 1.0 and 0.12

- aiida_vasp/io/parser.py
- aiida_vasp/parsers/vasp.py
- aiida_vasp/utils/delegates.py
- aiida_vasp/utils/tests/test_delegate.py
The delegate decorator introduced a global list of FileParsers on the `VaspParser` class leading to two instances of the `VaspParser` sharing the same set of FileParsers. This has caused issues with `VaspParser` instances being interconnected in a case, where they have been instantiated successively from the same import of `VaspParser`. 
This fix will replace the delegate decorator with the `Delegate` class, which is supposed to be just a callable list. This one can be instantiated per instance of the `VaspParser` and should solve the above stated issue.
> Fix Issue #160: replaced delegate decorator with a callable list

- aiida_vasp/workflows/base.py
- setup.json
should unblock all PRs that are stuck due to prospector 1.0 throwing a KeyError.
prospector has released 1.0, which throws the following error:
```
Traceback (most recent call last):
File "/home/hauselmann/miniconda2/envs/aiida-dev/bin/prospector", line 11, in <module>
sys.exit(main())
File "/home/hauselmann/miniconda2/envs/aiida-dev/lib/python2.7/site-packages/prospector/run.py", line 174, in main
prospector.print_messages()
File "/home/hauselmann/miniconda2/envs/aiida-dev/lib/python2.7/site-packages/prospector/run.py", line 132, in print_messages
formatter = FORMATTERS[output_format](self.summary, self.messages, self.config.profile)
KeyError: None
```
There is already an issue on their repo, until this is …
> pin prospector, add missing docstring

- aiida_vasp/io/vasprun.py
- aiida_vasp/parsers/vasp.py
fixes: #179 
blocks: #175 
is blocked by:
This is a quick fix for #179, which prevents requesting 'forces' for parsing in the current implementation. The current implementation works under the following two assumptions:
- The 'forces' quantity is stored in the 'output_parameters' node in the QE plugin.
- The quantities that will be stored in 'output_parameters' can be determined by setting `'output_params': [<quantities>]`.
This system may be changed later, if those requirements change.
> Fix: #179 requesting forces as part of 'output_parameters'

- aiida_vasp/commands/options.py
- aiida_vasp/commands/potcar.py
- aiida_vasp/utils/aiida_utils.py
fixes:
blocks:
is blocked by:
AiiDA-core recently moved the `verdi_data` click command group and added some reusable click options. This PR adapts to those changes while keeping backwards compatibility.
> fix the potcar command to work with aiida develop

- aiida_vasp/io/chgcar.py
- aiida_vasp/io/doscar.py
- aiida_vasp/io/eigenval.py
- aiida_vasp/io/kpoints.py
- aiida_vasp/io/outcar.py
- aiida_vasp/io/poscar.py
- aiida_vasp/io/vasprun.py
- aiida_vasp/io/wavecar.py
- aiida_vasp/parsers/parser_manager.py
- aiida_vasp/parsers/quantity.py
- aiida_vasp/parsers/tests/test_vasp_parser.py
fixes:
blocks:
is blocked by:
The 'parsers' card in the quantity definitions was a relict from the first rework of the `VaspParser` and it was intended to be used for setting the FileParsers that are required to parse a quantity. This has become obsolete/redundant in the current iteration of the VaspParser. 
Instead of using `parsers` to set the correct FileParsers for a quantity, now a quantity will have a `file_name` that is set dynamically based on the file name of the corresponding FileParser.
> Removed obsolete/redundant 'parsers' card from quantity_definitions

- aiida_vasp/parsers/quantity.py
- aiida_vasp/parsers/tests/test_vasp_parser.py
- aiida_vasp/parsers/vasp.py
(Potentially) fixes:
#199 
blocks:
#201 
is blocked by:
The problem is that in `test_vasp_parser` the 'quantity3' `ExampleFileParser` lists `quantity_with_alternatives` as prerequisite. However `ExampleFileParser` does not define 'quantity_with_alternatives' itself. It will only be automatically generated when `quantity1` is processed before `quantity3`, because `quantity1` has `quantity_with_alternatives` as an alternative. And for undefined 'alternatives' dummy quantities will be generated
> Fixed a bug with the ordering of the quantities in ExampleFileParser

- README.rst
fix: #200 
blocked by: #199 
Some links were pointing to the old location (DropD/aiida-vasp) of the repo. Those have been changed.
> fix links in README to point to the aiida-team repo

- .travis.yml
fixes:
#224 
blocks:
is blocked by:
To enable longer runs than 10 minutes on Travis. Typically some workchain tests takes some time to complete and the default 10 minutes is not sufficient. The time out is now 20 minutes, but can be increased by adding a number after `travis_wait`.
> Enable longer than 10 minute runs on Travis (now 20 minutes)

- aiida_vasp/workchains/relax.py
fixes:
blocks: workchain
is blocked by:
When I want set ISIF=5 to have shape_only relax, without setting `relax_parameters` (Line 229), `self.inputs.positions.value==False` cause `ibrion==-1` which don't update the structure.
> relax-wc _set_ibrion to -1 only when p,s,v all False

- aiida_vasp/calcs/tests/test_vasp.py
- aiida_vasp/calcs/vasp.py
- aiida_vasp/parsers/base.py
- aiida_vasp/parsers/quantity.py
- aiida_vasp/parsers/tests/test_base_parser.py
- aiida_vasp/parsers/tests/test_vasp_parser.py
- aiida_vasp/parsers/vasp.py
- aiida_vasp/utils/fixtures/__init__.py
- aiida_vasp/utils/fixtures/calcs.py
fixes:
#241 
blocks:
is blocked by:
In order to enable automatic deletion of files after parsing `retrieve_temporary_list` is available in AiiDA. This replaced the `retrieve_list` which do not delete any file after parsing is completed. The current behavior is that all files are delated after parsing unless specific filenames are added using `ADDITIONAL_RETRIEVE_LIST`.
> Introduced retrieve_temporary_list

- aiida_vasp/workchains/converge.py
- aiida_vasp/workchains/relax.py
fixes:
#289
blocks:
is blocked by:
Due to nan entries the `max` function failed and the relaxation workchain
did not work as expected. This is now fixed, we keep the nan, but act
on the raised `RuntimeWarning` from numpy and force the convergence
to not be complete if this in encountered. An update to the plane wave
and k-point convergence workchain is also performed in order to enable a final
run using relaxation and the converged plane wave and k-point cutoffs.
> Fixed issue with analysing positional lengths in relaxation workchain

- aiida_vasp/workchains/converge.py
fixes:
blocks:
is blocked by:
Due to the transition to namespaces we here fix the convergence data, which now reside in the `converge.data` namespace.
> Updated convergence data output to rest in the converge namespace

- aiida_vasp/workchains/relax.py
fixes:
#299
blocks:
is blocked by:
`ISIF=1` was stuck in the code, but it is better for us to use `ISIF=2` to give more info on the stress tensor, which is also the VASP default.
> Changed ISIF from 1 to 2

- aiida_vasp/workchains/converge.py
- aiida_vasp/workchains/master.py
- examples/run_bands.py
fixes:
#297 
blocks:
is blocked by:
We needed to remove the relaxation flag during convergence runs and re enable the relaxation flags for the final relaxation.
> Fixed problem of relaxation override

- aiida_vasp/workchains/converge.py
- aiida_vasp/workchains/tests/test_converge_wc.py
fixes:
#308 
blocks:
is blocked by:
Replaced `convergence_data` with the updated `converge.data` which was not included when we moved to namespaces in the input and output.
> Replaced old convergence_data

- aiida_vasp/utils/extended_dicts.py
- aiida_vasp/utils/parameters.py
- aiida_vasp/utils/tags.yml
- aiida_vasp/utils/tests/test_extended_dicts.py
- aiida_vasp/utils/tests/test_parameters.py
- aiida_vasp/utils/workchains.py
- aiida_vasp/workchains/converge.py
- aiida_vasp/workchains/relax.py
- aiida_vasp/workchains/tests/test_converge_wc.py
- aiida_vasp/workchains/tests/test_relax_wc.py
- aiida_vasp/workchains/vasp.py
- examples/run_converge.py
- examples/run_relax.py
- examples/run_vasp_lean.py
In order to open for the use of the workchains in other codes, we here decouple the workchains and the VASP specific parameters. In the workchains we use AiiDA/workchain specific parameters, which is translated at the code specific workchain in the workchain stack to code specific parameters. This concept can also be utilized by other codes.
fixes:
blocks:
is blocked by:
This pull request decouples VASP specific parameters in the relaxation and converge workchain. This opens for more code agnostic workchain layouts.
> Generalization of workchains

- aiida_vasp/workchains/converge.py
- aiida_vasp/workchains/relax.py
- aiida_vasp/workchains/tests/test_converge_wc.py
- aiida_vasp/workchains/vasp.py
- aiida_vasp/workchains/verify.py
To comply with the update https://github.com/aiidateam/aiida-core/pull/3466 we here incorporate lambda on all input nodes that are of an AiiDA data type. This is done to make it clear that we want to supply a immutable object as input. This also fixes the problem of not being able to run consequetive workchain tests, so in this PR all of the present workchain tests are finally enabled. In addition this PR fixes the previous problems of not being able to build RTD due to the need of a backend. Please consult https://github.com/aiidateam/aiida-core/pull/3466 and reference therein for additional details.
fixes:
blocks:
is blocked by:
None of the above but …
> Add lambda on input defaults

- aiida_vasp/calcs/tests/test_vasp.py
- aiida_vasp/calcs/vasp.py
- aiida_vasp/commands/mock_vasp.py
- aiida_vasp/parsers/tests/test_vasp_parser.py
- aiida_vasp/utils/fixtures/data.py
- setup.json
The always retrieve files are now stored as a default. This can be changed by setting ALWAYS_STORE to False in the settings, or as before specify ALWAYS_RETRIEVE_LIST and ALWAYS_RETRIEVE_TEMPORARY_LIST, also in settings. A few tests to tests different combinations have been introduced.
Partly fixes #320.
In order to make it easier for users to do post processing etc. we here enable the storage of the parsed files by default.
> Make sure always retrieve files are stored by default

- aiida_vasp/calcs/base.py
- aiida_vasp/calcs/vasp.py
- aiida_vasp/parsers/base.py
- aiida_vasp/utils/fixtures/calcs.py
- aiida_vasp/utils/parameters.py
- aiida_vasp/workchains/vasp.py
- [x ] ready to be reviewed and merged (as soon as tests have passed)
fixes:
#320 to some extend. A check of `parser_name` is added to `VaspCaculation`.
blocks:
is blocked by:
#320 what about the default file retrieve behaviour - permanent or temporary? 
In addition to the above, this PR contains the following minor fixes:
* Fixed a bug where `ParameterMassage` does not convert upper case keys properly. 
* Fixed a bug where `VaspParser` throws an error whenever `retrieved_temporary` is absent - it should only do so when both the temporary and permanent retrieves are not there.
> #320 related stuff and other minor fixes

- aiida_vasp/calcs/immigrant.py
- aiida_vasp/calcs/tests/test_immigrant.py
fixes:
#313 
Upon enabling to use an exclude list for the retrieved files in AiiDA, the call was moved to `presubmit`, which we did not call in our `run` override. An explicit call has been added which fixes the failed immigrator tests. In addition, both tests were modified.
> Fixed immigrator by adding explicit call to presubmit

- aiida_vasp/calcs/vasp.py
- aiida_vasp/parsers/file_parsers/incar.py
- aiida_vasp/utils/parameters.py
- aiida_vasp/utils/tests/test_parameters.py
- aiida_vasp/workchains/bands.py
- aiida_vasp/workchains/converge.py
- aiida_vasp/workchains/relax.py
- aiida_vasp/workchains/tests/test_bands_wc.py
- aiida_vasp/workchains/tests/test_converge_wc.py
- aiida_vasp/workchains/tests/test_relax_wc.py
- examples/run_bands.py
- examples/run_converge.py
- examples/run_relax.py
- examples/run_vasp_lean.py
- examples/run_vasp_prep_w90.py
fixes:
#333 
blocks:
In order to be able to check any supplied override parameters we needed to move these into a dedicated namespace. This namespace, now also corresponds well to the workchain where the conversion takes place.
> Moved override input parameters into a namespace

- aiida_vasp/calcs/tests/test_vasp.py
- aiida_vasp/parsers/file_parsers/incar.py
- aiida_vasp/parsers/file_parsers/tests/test_incar_parser.py
- aiida_vasp/utils/parameters.py
- aiida_vasp/utils/tests/test_parameters.py
fixes: #332 
blocks:
is blocked by:
Try to fix #332, catch invalid INCAR tags at both `VaspCalculation` and `VaspWorkChain` level.
> Catch invalid INCAR tags

- .ci/enable_ssh_localhost.sh
- .github/workflows/ci.yml
- tox.ini
Here we enable GitHub Actions and Codecov for running tests.
In the transition from travis-ci.org to travis-ci.com we never got the checks to be shown for pull requests. Also, having everything in one place on GitHub Actions is at this point beneficial. Due to the lack of non LCOV file support (and the fact that we cannot access secrets from forks in GitHub Actions at the moment) we needed to move the coverage analysis to Codecov from Coveralls.
> Enable GitHub Actions and Codecov

- aiida_vasp/calcs/vasp.py
- aiida_vasp/parsers/base.py
- aiida_vasp/utils/fixtures/calcs.py
Adds a check to see if there are any VASP output files present in the `retrieved` and `retrieved_temporary` folders. This is a rather strong test to check that the code did not execute properly. Even though we introduce parsing of the standard stream from VASP, that parsing could fail, so it is convenient to check this first. Also, if there are no files (including standard stream) then there is no point to parse.
> No output files break

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
Here we implement a nightly test against `aiida-core` develop branch in order to detect if something brakes upstream that we need to take action on. The build runs at midnight, but depending on where it runs, it can be shifted due to time differences.
> Added nightly test against aiida-core

- .pre-commit-config.yaml
My system can't reach repos in .pre-commit-config.yaml with `git://` probably because the port is closed by the institute. `https://` works using the provided proxy server.
> Replace git: by https: in .pre-commit-config.yaml

- aiida_vasp/calcs/base.py
- aiida_vasp/calcs/immigrant.py
- aiida_vasp/calcs/tests/test_vasp.py
- aiida_vasp/calcs/vasp.py
- aiida_vasp/commands/mock_vasp.py
- aiida_vasp/commands/potcar.py
- aiida_vasp/commands/tests/test_potcar_cmd.py
- aiida_vasp/data/potcar.py
- aiida_vasp/data/tests/test_potcar.py
- aiida_vasp/data/tests/test_potcar_walker.py
- aiida_vasp/parsers/file_parsers/parser.py
- aiida_vasp/parsers/file_parsers/potcar.py
- aiida_vasp/parsers/file_parsers/tests/test_potcar_parser.py
- aiida_vasp/utils/fixtures/data.py
- aiida_vasp/utils/fixtures/environment.py
- aiida_vasp/utils/general.py
- ops/update_version.py
- setup.json
fixes:
#395 #264
blocks:
is blocked by:
Here we remove the `py` dependency and replacing it with the standard `pathlib` and `shutil` (for copy operations).
> Removed py.path dependencies

- setup.json
Due to updates in `aiida_core==1.4.0, 1.4.1`, we need to exclude these versions due to the fact that files in the exclude list was allowed to reside in the repository.
> Remove AiiDA 1.4.0 and 1.4.1 as this allow POTCAR to rest in repository

- aiida_vasp/calcs/vasp.py
When using `calcinfo.local_copy_list.append`, we use the relative path for dst, so this should just be "CHGCAR" and "WAVECAR".
Otherwise when trying to write these files, AiiDA runs into the following errors: (VaspCalculation is stuck on upload
and verdi process report gives:)
Tested with this code fix and works as it should.
I think this issue may have occurred because of a previous update in `calcinfo.local_copy_list.append`.
fixes:
blocks:
is blocked by:
> Use relative path for `dst` when writing CHGCAR and WAVECAR

- aiida_vasp/calcs/base.py
- aiida_vasp/calcs/vasp.py
Previously the copying of the restart folder will copy all files
including the output files such as vasprun.xml and OUTCAR. Which
can result in incorrect outcome if the remote job is kill.
The copy is now limited to CHGCAR and WAVECAR, and the remote folder
is checked for constructing the list.
The `write_additonal` method now simply checks the existence of the
files in the copy list.
fixes:
#414 
blocks:
is blocked by:
> Use positive match for restart folder copy

- aiida_vasp/data/archive.py
- aiida_vasp/data/potcar.py
- aiida_vasp/utils/fixtures/data.py
fixes:
#420
blocks:
is blocked by:
Fix deprecation warnings issued by `aiida-core` related to using `open` method of a `Node` class without going through the context manger interface (e.g. `with ....`). 
Also, fix a bug in the tests related to `copytree` with the non-existing destination. This somehow works just fine with the older ubuntu github action environment, and also on my local computer. However, it started to fail after an image update. I have got no idea why it is the case, but having the folder (`potential`) created in the first place seems to be the sensible thing to do and does no …
> Fix potcar warnings

- aiida_vasp/assistant/parameters.py
- aiida_vasp/assistant/tests/test_parameters.py
- aiida_vasp/calcs/immigrant.py
- aiida_vasp/calcs/tests/test_vasp.py
- aiida_vasp/calcs/tests/test_vasp2w90.py
- aiida_vasp/calcs/vasp.py
- aiida_vasp/calcs/vasp2w90.py
- aiida_vasp/utils/fixtures/calcs.py
- aiida_vasp/utils/fixtures/data.py
- aiida_vasp/workchains/converge.py
- aiida_vasp/workchains/relax.py
- aiida_vasp/workchains/tests/test_bands_wc.py
- aiida_vasp/workchains/tests/test_converge_wc.py
- aiida_vasp/workchains/tests/test_relax_wc.py
- aiida_vasp/workchains/tests/test_vasp_wc.py
- aiida_vasp/workchains/vasp.py
- aiida_vasp/workchains/verify.py
- examples/run_bands.py
- examples/run_converge.py
- examples/run_relax.py
- examples/run_vasp_lean.py
When allowing selective dynamics flags in PR #408 some bugs were introduced which caused e.g. the flags to be not put correctly in the code namespace. This is fixed and in addition we introduce the following specification: the namespaces allowed on the input parameters are restricted. This means that if the user want sto override a parameter (send it straight to VASP) it needs to be put in the code namespace. If any parameter is detected on the input parameter root and it is not in the allowed namespace, an exception will be raised. While updating we also disconnected the massager from the workchain, which was previously supplied to get access to the exit codes. Now, we instead raise exceptions with a sensible text and then catch this in the VASP workchain …
> Update of parameter massager

- doc/source/calculations/vasp.rst
- doc/source/concepts/parameters.rst
- doc/source/index.rst
- doc/source/workchains/vasp.rst
Here we add documentation on how the parameter passing works and how to control it. In addition we add documentation for the input node change on the VASP calculation.
> Added documentation on how to use parameters

- aiida_vasp/calcs/vasp.py
- aiida_vasp/parsers/file_parsers/vasprun.py
- aiida_vasp/parsers/settings.py
- aiida_vasp/parsers/vasp.py
- aiida_vasp/workchains/vasp.py
- tox.ini
Initial attempt to add `energies_sc` output node to store SCF energies information during SCF
This works with the latest AiiDA-core develop and AiiDA-VASP develop. Tests have not written yet.
I added `energies_sc` output node to `VaspCalculation` and `VaspWorkChain`. AiiDA type is the `ArrayData` and two (or more) datasets of `energy_no_entropy` (and the other energy types when specified) and 'sc_iters'. The former contains the energies of all SCF steps in all ionic steps. The iteration numbers of the ionic steps can be different, so the energy values are simply concatenated. To split this 1D data array into the bunches of respective ionic steps, `sc_iters` is stored as 1D array of integers where each integer …
> Initial attempt to add energies_sc to store SCF energies

- aiida_vasp/calcs/vasp.py
In PR #428 a bug was introduced in which the calculation would fail when trying to set selective dynamics.
This makes the passing more explicit to eliminate any possible issues.
> Changing the way in which the selective dynamics are passed to the vasp calculation

- aiida_vasp/parsers/file_parsers/chgcar.py
- aiida_vasp/parsers/file_parsers/doscar.py
- aiida_vasp/parsers/file_parsers/eigenval.py
- aiida_vasp/parsers/file_parsers/incar.py
- aiida_vasp/parsers/file_parsers/kpoints.py
- aiida_vasp/parsers/file_parsers/outcar.py
- aiida_vasp/parsers/file_parsers/parser.py
- aiida_vasp/parsers/file_parsers/poscar.py
- aiida_vasp/parsers/file_parsers/stream.py
- aiida_vasp/parsers/file_parsers/tests/test_incar_parser.py
- aiida_vasp/parsers/file_parsers/vasprun.py
- aiida_vasp/parsers/file_parsers/wavecar.py
issue #434
I rewrote with explicit checks of keyward arguments and corresponding actions in the `__init__` method of each specific file parser.
The following test is commented out.
https://github.com/aiida-vasp/aiida-vasp/blob/2d0dc046b4dcb635ca09fd9163c59284925e0e77/aiida_vasp/parsers/file_parsers/tests/test_incar_parser.py#L62-L73
> Remove _init_with_somevalue (issue #434)

- aiida_vasp/data/potcar.py
Now getting the PotcarFileData from PotcarData is only through matching SHA512. Since the SHA512 is only computed from the file content, matching a PotcarFileData with different other attributes does not change the end result. This fixes inconsistency when uploading family containing POTCAR that does not exist in the database but a PotcarData does exist (#417), giving rise to stale `PotcarData` nodes. 
This PR also makes it possible to use imported `PotcarData` nodes in new calculations as long as the actual POTCAR file has been deposited in the database. 
fixes:
#417
blocks:
is blocked by:
> Make PotcatData -> PotcarFileData only match sha512

- .github/workflows/ci.yml
- aiida_vasp/calcs/tests/test_vasp.py
- aiida_vasp/calcs/vasp.py
- aiida_vasp/utils/bands.py
The entry `stdout_name` and `join_files` should be placed under
`CodeInfo` rather than `CalcInfo` in order the activate redirection
of STDOUT and STDERR which is needed for parsing notifications.
This fixes the warnings: 
> | The quantity notifications has been requested for parsing, however the following files required for parsing it have not been retrieved: vasp_output.
and missing notifications output of the `VaspCalculation`. 
fixes:
blocks:
is blocked by:
> Fix a bug where standout/err redirection

- doc/source/concepts/immigrations.rst
The way to give `resources` in concepts/immigrations script was fixed.
I changed from `run` to `submit` because I think this is more possible usage. I also changed `inputs` to `builder` because `VaspCalculation.immigrant` returns `builder`, but this may be unnecessary change.
> Minor fix of concepts/immigrations doc

- aiida_vasp/parsers/settings.py
The key fermi_level and symmetries are removed from the list of
default misc output quantities. The former is not always present
if DOS calculation is not performed. The latter is rarely useful
and causes confusions.
This should make the relaxation workchain run fine.
> Revise the default misc output - remove fermi_level and symmetries

- aiida_vasp/parsers/vasp.py
Use a dictionary to hold the instantiated parser objects so we don't instantiate new file parser object for each quantity to be
parsed.
I noticed this testing the parser code. For example, the `vasprun.xml` is actually parsed multiple times as there are multiple quantities from that file, which is unnecessary. We should just keep the instantiated file parser object and reuse it. 
I recall this was mentioned in one of the meetings.
> Cache instances of file parsers when parsing the output

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- aiida_vasp/workchains/converge.py
Ensuring that the final relaxation is performed if the user wishes so. Addresses #466
Fixing an issue in which the convergence will be performed even if pwcutoff was given in the electronic parameter space.
Fixing an issue in which the structure was not being exposed as an input due to #301.
fixes: #466 
blocks:
is blocked by:
> Allowing final structural relaxation in the converge workchain 

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
The CI configuration uses `ubuntu-latest` which recently became Ubuntu
Focal Fossa (20.04) which no longer has `postgres-10` available, but
instead provides `postgres-12`. The simplest solution is to just install
`postgres` without specifying an explicit version since we should
support all existing versions.
fixes:
blocks:
is blocked by:
> CI: Use `postgres` since update to Ubuntu Focal 20.04

- .github/workflows/ci.yml
- aiida_vasp/utils/fixtures/data.py
- aiida_vasp/utils/fixtures/environment.py
This PR fixes plugin tests using an existing test profile.
The test profile manager can be a barebone `ProfileManger` if running
with an existing profile. It does not have a root directory defined.
If that is the case, just print the profile name instead.
fixes:
#471
> Fix a the fresh_aiida_env fixture

- aiida_vasp/calcs/tests/test_vasp.py
- aiida_vasp/commands/mock_vasp.py
- aiida_vasp/utils/aiida_utils.py
The `get_data_class` utility was decorated with `with_dbenv`. This
function is supposed to load the database environment if it is not
already loaded. However, a bug in that function causes it to load the
database to be loaded everytime. This causes a simple call like:
RelaxWorkChain.get_builder()
to last 10 seconds, instead of being almost instantaneous.
Now, the bug should of course be addressed in `aiida-core` but the
database really doesn't have to be loaded to load the data classes, so
it is best to remove the decorator entirely. The correct profile will be
instantiated automatically as soon as an instance is created of any of
the loaded data classes.
> Remove `with_dbenv` decorator from `get_data_class`

- .github/workflows/ci.yml
- aiida_vasp/parsers/file_parsers/tests/test_vasprun_parser.py
- aiida_vasp/parsers/node_composer.py
- setup.json
In some cases, VASP can generate numerical results with NaN. For example, having `maximum_force` equal to NaN in some hybrid functional band structure calculations that involve a regular grid + zero-weighted kpoints. 
However, `aiida-core` is not able to store these numerical values as attributes due to the limitation of the underlying SQL engine, resulting in exceptions. This PR adds and additional cleaning steps before composing the `Node` for storage. The problematic numerical values are represented by string instead.
> Sanitize nan and inf values before storing `Dict` nodes

- aiida_vasp/assistant/tests/test_parameters.py
- aiida_vasp/parsers/file_parsers/tests/test_incar_parser.py
- aiida_vasp/parsers/file_parsers/tests/test_outcar_parser.py
- aiida_vasp/parsers/file_parsers/tests/test_vasprun_parser.py
- aiida_vasp/parsers/tests/test_vasp_parser.py
- aiida_vasp/utils/tests/test_band_info.py
- aiida_vasp/workchains/tests/test_vasp_wc.py
fixes: #493
blocks:
is blocked by:
When comparing the floating-point numbers in tests, use the `pytest.approx` method. It has a default relative tolerance of 1e-6, which should be OK for most cases.
> Compare floats with pytest.approx in tests

- aiida_vasp/commands/potcar.py
- aiida_vasp/commands/tests/test_potcar_cmd.py
- aiida_vasp/data/potcar.py
- aiida_vasp/data/tests/test_potcar.py
- aiida_vasp/utils/extended_dicts.py
- aiida_vasp/utils/fixtures/data.py
- aiida_vasp/utils/workchains.py
- aiida_vasp/workchains/tests/test_bands_wc.py
- pytest.ini
- setup.json
fixes: 
blocks:
is blocked by:
This is still a work in progress. I have made code changes to remove various deprecation warnings that were issued by aiida-core 1.x. 
The major change is the implementation of the pseudopotential family - correct use of the new (not anymore!) `Group` class will break the backward compatibility, but this can be fixed easily by performing a migration on the existing groups.
> [WIP] Simple fix for deprecate warnings and Group implementation

- aiida_vasp/parsers/settings.py
- aiida_vasp/parsers/tests/test_vasp_parser.py
- aiida_vasp/workchains/vasp.py
fixes: #497 #498 
blocks:
is blocked by:
Active the check for critical files (OUTCAR and vasprun.xml). A calculation that does not have these two files will behave the corresponding return code `ERROR_CRITICAL_MISSING_FILE`. 
This also fixes the by-pass for ignore the transient NELM breach, it should be applied in all cases, not just for specific return codes. Otherwise, a finished calculation with transient breaches may still result in an exit code, even if the user requested to by pass it.
> check for critical missing files and fix the NELM breach by-pass

- .github/workflows/ci.yml
- aiida_vasp/calcs/tests/test_vasp.py
- aiida_vasp/parsers/settings.py
- aiida_vasp/parsers/tests/test_parser_settings.py
- aiida_vasp/parsers/tests/test_vasp_parser.py
- aiida_vasp/parsers/vasp.py
- aiida_vasp/workchains/vasp.py
- doc/source/concepts/parsing.rst
- setup.json
fixes:
#483
blocks:
is blocked by:
Allow the user to pass a list of notifications to be ignored, or ignore all notifications that make the calculation end up in `ERROR_VASP_CRITICAL_ERROR`. These are passed under the `parser_settings` of the `settings` input port.
Note that fine-tuned per-case treatment can be defined as a method of the `NotificationComposer`.
> allow some critical notifications (errors) to be ignored

- aiida_vasp/workchains/immigrant.py
- aiida_vasp/workchains/vasp.py
This fixes an accidental issue with aiida-core 1.6.5. Previously, the outputs are repeated explicitly, which is now replaced by
a `expose_outputs` call.
On aiida-core > 1.6.5, the nested outputs are now handled correctly, and `BaseRestartWorkChain` uses this to check for
required outputs for the underlying calculation node. This implies that the outputs should be added with the `expose_outputs` method.
Fixes:
#518
> Use `expose_outputs` for VaspWorkChain

- setup.json
When setting up aiida-core v1.6.5 (latest release at this moment) and then aiida-vasp installation, pymatgen is re-installed because of version mismatch of `setup.json` of these two. This PR is just use the same pymatgen version dependency as the aiida-core v1.6.5.
> Same pymatgen version dependency as aiida-core v1.6.5

- aiida_vasp/parsers/file_parsers/tests/test_vasprun_parser.py
- aiida_vasp/parsers/file_parsers/vasprun.py
- [] ready to be reviewed and merged (as soon as tests have passed)
- [x ] work in progress (early feedback welcome)
fixes: #524 
Previously, the total energies returned are those calculated by the
electronic routine. They do not include any additions added in the
ionic loop, such as those from dispersion corrections and external
pressure.
This commit makes sure the energies are those returned by the ionic
routine and those from the electronic routines are named with
`_electronic` suffixes, this ensures backward compatibility - so the
total energy is still accessible under the same item stored in `total_energies`.
The key is what we call it in the …
> make sure total energies returned include pressure and other terms

- aiida_vasp/workchains/vasp.py
fixes: #538 
The ionic convergence checkout should respect the `CHECK_IONIC_CONVERGENCE` flag in the settings that signals if the parser should be checking the ionic convergence and set exit_code accordingly. If the parser ignores it, the workchain should also ignore it.
Otherwise, the user can manually disable the handler with `handler_overrides` input to the workchain. But I can not think of a practical scenario where the parser ignores it but the workchain does not.
> allow bypassing ionic check with settings

- setup.json
fixes:
#540
We pin the `parsevasp` version to a commit before the updates related to the work on the parsing infrastructure started. This way, the development branch of `aiida-vasp` is not broken.
> Pinned parsevasp to commit before work on parsing infrastructure started

- .travis.yml
- setup.json
- tox.ini
fixes:
#542
Removed all things related to Python 3.6 and also added `python_requires`. Implicitly we depend on this as we depend on `aiida_core`, but maybe nice to have it explicitly in the file.
> Removed Python 3.6 support

- aiida_vasp/parsers/file_parsers/tests/test_vasprun_parser.py
- aiida_vasp/parsers/file_parsers/vasprun.py
- aiida_vasp/test_data/basic/vasprun621.xml
- aiida_vasp/utils/fixtures/__init__.py
- aiida_vasp/utils/fixtures/data.py
This causes error because `etype` is not a dict but a list.
https://github.com/aiida-vasp/aiida-vasp/blob/50f025e4df61c3cbc627ebef53ad624058ccf464/aiida_vasp/parsers/file_parsers/vasprun.py#L591
> Minimum fix of parsing energy for non-VASP5

- aiida_vasp/calcs/vasp.py
One line fix.
To be consistent between `NODES` in `settings.py` and `VaspCalculation` output ports, I think `occupancies` port should be removed.
> Remove occupancies output port from VaspCalculation

- .github/workflows/ci.yml
* Run code coverage with pytest in tox only for matrix.python == '3.8'
* Fix if statements to check matrix.python
* Replace coveralls with codecov and pytest-cov
fixes: #563
> Avoid redundant second pytest run in github actions

- aiida_vasp/workchains/converge.py
- aiida_vasp/workchains/tests/test_converge_wc.py
The results of pwcutoff and k-point convergence tests are stored in
AiiDA's Dict. Thus, we cannot use np.nan for representing failed
runs because nan values in Dict raise error when they are stored. To
avoid this situation, this fix add a new boolean entry in `pw_data` and `k_data`
that represents the corresponding run successed or not.
fixes: https://github.com/aiida-vasp/aiida-vasp/issues/558
blocks:
is blocked by:
> Avoid np.nan in convergence data

- aiida_vasp/calcs/vasp.py
- aiida_vasp/parsers/node_composer.py
- aiida_vasp/parsers/settings.py
- aiida_vasp/parsers/tests/test_vasp_parser.py
- aiida_vasp/parsers/vasp.py
fixes: issue #552
This is a fix to support custom outputs. For example
```python
"add_custom_outputs": {
"type": "float",
"quantities": [
"fermi_level",
],
"link_name": "fermi_level",
},
```
or
```python
"add_custom_outputs": {
"type": "float",
"quantities": [
"fermi_level",
],
"link_name": "custom_outputs.fermi_level",
},
```
This attaches `Float(fermi_level)` to `custom_outputs.fermi_level`.
- Custom outputs are attached to "custom_outputs" output_namespace.
- Add float, int, str supports of NodeComposer.
Currently `xxxxx` of `add_xxxxx` is used for the dict key to handle the node information dictionaries. `xxxxx` is used only searching the key in `NODES` (`settings.py`), and not used anywhere else (except …
> Made custom_outputs work (issue #552)

- aiida_vasp/utils/fixtures/data.py
It is safe to set job poll interval of computer to zero in testing. This
fix sets it to zero to reduce time to run CI.
fixes: https://github.com/aiida-vasp/aiida-vasp/issues/564
There is an alternative way to set job poll interval, to use `aiida_localhost`, not aiida-vasp's localhost fixture.
However, that direction seems to need further refactoring on the whole testing infrastructure of aiiva-vasps.
Thus, for now, this PR does not choose to replace aiida-vasp's localhost fixture with `aiida_localhost`.
> Set job poll interval to zero in localhost fixture

- .github/workflows/ci.yml
- ops/update_version.py
- tox.ini
Fixes #574
Here we move `pre-commit` into `tox` so that we can also run it in a reproducible manner locally with `tox -e pre-commit`. This would not rely on your locally installed `pre-commit` version, or any version conflicts that might appear from the `pre-commit` config and deps for your setup.
> Moved pre-commit tests into tox

- aiida_vasp/workchains/relax.py
There was a small issue in which the relax workchain would fail if one asked for the `site_magnetization`
> Fixing a small issue with the magnetization in the relax workchain

- aiida_vasp/utils/workchains.py
- aiida_vasp/workchains/vasp.py
It can be empty for various reason, this should be not cause an
exception..
fixes:
blocks:
is blocked by:
Just a small fix on setting the site magnetization.
Sometimes the output of site_magnetization can be emtpy, e.g. non-spin polarised calculations. This can happen when someone launches an array of calculation that are mixed in `ISPIN` values yet having other input parameters identical....
> Catch cases where site_magnetization output can be empty

- aiida_vasp/parsers/content_parsers/base.py
- aiida_vasp/parsers/content_parsers/tests/test_base_file_parser.py
With AiiDA 2.0, the handler returned by `node.base.repositiory.open` may be of any class, and it is backend dependent. Hence, we need to remove the overly cautious check of passed handler type. 
This did not trigger test failure probably because when parsing calculation results before they are stored in the storage backend, the handler return is still of a actual file on the disk.
> Remove check of handler type

- aiida_vasp/parsers/content_parsers/kpoints.py
The KPOINTS parser in `parsevsap` now probes the `generating_vectors` key, should make it default ot None.
Otherwise, the KPOINTS file cannot be written for VASP calculation.
fixes:
blocks:
is blocked by:
> Fix compatibility with parsevasp development branch

- aiida_vasp/workchains/relax.py
I, the author consider this PR is ready to be reviewed. Probably input variable name (tentatively `perform_static`) should be reconsidered. Test is not written yet. Tox doesn't work on my environment, maybe due to behind proxy...
In the relax workchain, it may be useful if we can omit running the final static calculation. This PR adds the option.
> Option to omit static run in relax workchain

- aiida_vasp/calcs/vasp.py
- pyproject.toml
Fixes the `custom_outputs` to be a non-required output as the reports where complaining about it.
> Disabled required for custom output namespace

- .github/workflows/nightly.yml
It was installing the `develop` branch of `aiida-core` but the main
branch has been changed to `main` since `aiida-core==2.0`. Also, since
that version, `reentry` has been removed so `reentry scan` is no longer
necessary.
> DevOps: Fix the nightly workflow

- .pre-commit-config.yaml
- aiida_vasp/calcs/tests/test_vasp.py
- aiida_vasp/calcs/vasp.py
- aiida_vasp/data/potcar.py
- doc/source/concepts/parameters.rst
fixes:
#611 
blocks:
is blocked by:
Ensure `validate_tags` to be off if `skip_parameters_validation` or `unsupported_parameters` are present in `.settings` input.
Also perform some minor update on the relevant documentation page.
> Respect settings on INCAR validation at Calculation Level

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
Updated the Github actions so that they use the Node.js 16 based ones. Fixes #631
> Updating the github actions so that they use the Node.js 16 based ones.

- readthedocs.yml
It seems only Python up and including `3.8` is supported at RTD without enabling for instance a testing image, so we lower the specified version in the config file.
> Dropped Python version for RTD

- .github/workflows/ci.yml
- MANIFEST.in
- pyproject.toml
Here we bump the dependency for `aiida-core` to `~=2.4` due to recent release. This removes Python 3.8 support,
which we also do here. We still keep the Python 3.8 usage on RTD as that is decoupled from local Python versions.
> Updated aiida core dependency

- codecov.yml
- [x} ready to be reviewed and merged (as soon as tests have passed)
In prep for the release, we increased the threshold due to large code changes. In the PR we reset it back.
> Dropping threshold for codecov after release

- CHANGELOG.rst
- aiida_vasp/calcs/vasp.py
- aiida_vasp/parsers/content_parsers/outcar.py
- aiida_vasp/parsers/content_parsers/vasprun.py
- aiida_vasp/parsers/neb.py
- aiida_vasp/parsers/tests/test_node_composer.py
- aiida_vasp/parsers/vasp.py
- aiida_vasp/utils/default_symbols.py
- aiida_vasp/utils/fixtures/data.py
- aiida_vasp/workchains/vasp.py
This is a cherry-pick of acc2a712d9e83eb420ec88a3e3c24d86ac9d8a22 which was released with `v2.2.0` but was never added to the main branch. As a result, the `aiida-common-workflows` now fail with `aiida-vasp>=3.0` which is necessary for AiiDA v2.0 compatibility. The commit in question added specific handlers for the `VaspWorkChain` that are missing in `aiida-vasp` v3.0. This is restored by cherry-picking the commit.
fixes:
blocks:
is blocked by:
> Porting fixes for ACWF v1.0 to the `develop` branch

- .github/workflows/ci.yml
- .github/workflows/validate_release_tag.py
The CI workflow is updated to trigger deployment of the package to PyPI when a new tag is pushed to the main repository and the pre-commit and tests have passed successfully. As a final check, the tag label is compared with the version defined in the `aiida_vasp/__init__.py` to make sure they match and prevent accidental incorrect tags.
For this to work, a secret needs to be generated in the PyPI account of `aiida-vasp` and this needs to be added on this repository under the name `PYPI_KEY`.
> Devops: Add continuous deployment to CI workflow

- .ci/enable_ssh_localhost.sh
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/validate_release_tag.py
- pyproject.toml
Refactoring the CI/CD workflows to ensure that they are easier to maintain. Moved the CD part of the workflows to its own file, remove deprecated parts of the workflows, and make changes to ensure that the tag validation works with the source layer of the repo.
> 701 refatcor the GitHub workflows to make them more maintenable
